GET http://localhost:8010/po/api/exercises

###

GET http://localhost:8010/po/api/exercises/workouts

###

GET http://localhost:8010/po/api/exercises/workouts/xOGfBAiTgWhPVsDCMlmsgUycU6D2

###

GET https://poverload-api.onrender.com/po/api/exercises?page=3

###

GET http://localhost:8010/po/api/workouts

###

POST http://localhost:8010/po/api/workouts
Content-Type: application/json

{
  "sets": {
    "1": { "weight": "body", "reps": "20", "overload": 12, "type": "text" }
  },
  "uid": "xOGfBAiTgWhPVsDCMlmsgUycU6D2",
  "exerciseId": "64c97c81e9d6fa793227f258"
}

# {
#   "exerciseId": "64c6cbc4b25f066f3b8194cf",
#   "sets": {
#     "1": {
#       "weight": 25,
#       "reps": 10
#     },
#     "2": {
#       "weight": 40,
#       "reps": 5
#     },
#     "3": {
#       "weight": 35,
#       "reps": 3
#     },
#     "4": {
#       "weight": 35,
#       "reps": 3
#     }
#   }
# }
